### ISSUE TITLE
Hy3DRenderMultiView "CUDA error: no kernel image is available for execution on the device"

### ISSUE THREAD

**Issue by mrabet** [kijai/ComfyUI-Hunyuan3DWrapper#105]
# ComfyUI Error Report
## Error Details
- **Node ID:** 79
- **Node Type:** Hy3DRenderMultiView
- **Exception Type:** RuntimeError
- **Exception Message:** CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Exception raised from c10_cuda_check_implementation at C:\actions-runner\_work\pytorch\pytorch\pytorch\c10\cuda\CUDAException.cpp:43 (most recent call first):
00007FF8D50091D900007FF8D5009130 c10.dll!c10::Error::Error [<unknown file> @ <unknown line number>]
00007FF8D5007A6A00007FF8D5007A10 c10.dll!c10::detail::torchCheckFail [<unknown file> @ <unknown line number>]
00007FF8E1D94E3F00007FF8E1D94B40 c10_cuda.dll!c10::cuda::c10_cuda_check_implementation [<unknown file> @ <unknown line number>]
00007FF8E1D9B10300007FF8E1D961F0 c10_cuda.dll!c10::cuda::warn_or_error_on_sync [<unknown file> @ <unknown line number>]
00007FF8E1D9638D00007FF8E1D961F0 c10_cuda.dll!c10::cuda::warn_or_error_on_sync [<unknown file> @ <unknown line number>]
00007FF8D4FCAAA300007FF8D4FCAA40 c10.dll!c10::StorageImpl::StorageImpl [<unknown file> @ <unknown line number>]
00007FFFE58E5A7F00007FFFE58E5340 torch_cpu.dll!at::DynamicLibrary::sym [<unknown file> @ <unknown line number>]
00007FFFE58E7DEE00007FFFE58E7DC0 torch_cpu.dll!at::detail::empty_generic [<unknown file> @ <unknown line number>]
00007FFFA829657500007FFFA8296490 torch_cuda.dll!at::detail::empty_cuda [<unknown file> @ <unknown line number>]
00007FFFA829646E00007FFFA82963B0 torch_cuda.dll!at::detail::empty_cuda [<unknown file> @ <unknown line number>]
00007FFFA83A5C7800007FFFA83A5C10 torch_cuda.dll!at::native::empty_cuda [<unknown file> @ <unknown line number>]
00007FFFAA0B803E00007FFFAA05CCF0 torch_cuda.dll!at::cuda::where_outf [<unknown file> @ <unknown line number>]
00007FFFA9FA653E00007FFFA9F374E0 torch_cuda.dll!at::cuda::bucketize_outf [<unknown file> @ <unknown line number>]
00007FFFE64A362C00007FFFE648C070 torch_cpu.dll!at::_ops::xlogy__Tensor::redispatch [<unknown file> @ <unknown line number>]
00007FFFE6513C9100007FFFE648C070 torch_cpu.dll!at::_ops::xlogy__Tensor::redispatch [<unknown file> @ <unknown line number>]
00007FFFE65EE1AE00007FFFE65EE0D0 torch_cpu.dll!at::_ops::empty_memory_format::redispatch [<unknown file> @ <unknown line number>]
00007FFFE686C64900007FFFE68492D0 torch_cpu.dll!at::_ops::view_as_real::redispatch [<unknown file> @ <unknown line number>]
00007FFFE686A56E00007FFFE68492D0 torch_cpu.dll!at::_ops::view_as_real::redispatch [<unknown file> @ <unknown line number>]
00007FFFE64A362C00007FFFE648C070 torch_cpu.dll!at::_ops::xlogy__Tensor::redispatch [<unknown file> @ <unknown line number>]
00007FFFE655B6B800007FFFE655B470 torch_cpu.dll!at::_ops::empty_memory_format::call [<unknown file> @ <unknown line number>]
00007FFFE5A1DD7900007FFFE59FEF10 torch_cpu.dll!at::functorch::reshape_dim_outof_symint [<unknown file> @ <unknown line number>]
00007FFFE5E4B3B600007FFFE5E4B2B0 torch_cpu.dll!at::native::zeros_symint [<unknown file> @ <unknown line number>]
00007FFFE6AE297A00007FFFE6ADB5F0 torch_cpu.dll!at::compositeexplicitautograd::view_copy_symint_outf [<unknown file> @ <unknown line number>]
00007FFFE6AB04FB00007FFFE6A663B0 torch_cpu.dll!at::compositeexplicitautograd::bucketize_outf [<unknown file> @ <unknown line number>]
00007FFFE631E2E500007FFFE631E210 torch_cpu.dll!at::_ops::zeros::redispatch [<unknown file> @ <unknown line number>]
00007FFFE6870B0C00007FFFE68492D0 torch_cpu.dll!at::_ops::view_as_real::redispatch [<unknown file> @ <unknown line number>]
00007FFFE686A44B00007FFFE68492D0 torch_cpu.dll!at::_ops::view_as_real::redispatch [<unknown file> @ <unknown line number>]
00007FFFE62B3A1000007FFFE62B3810 torch_cpu.dll!at::_ops::zeros::call [<unknown file> @ <unknown line number>]
00007FFF98AB5B8D00007FFF98AB56B0 custom_rasterizer_kernel.cp312-win_amd64.pyd!c10::ivalue::Object::operator= [<unknown file> @ <unknown line number>]
00007FFF98AD675E00007FFF98AD3340 custom_rasterizer_kernel.cp312-win_amd64.pyd!PyInit_custom_rasterizer_kernel [<unknown file> @ <unknown line number>]
00007FFF98AD32FD00007FFF98AB56B0 custom_rasterizer_kernel.cp312-win_amd64.pyd!c10::ivalue::Object::operator= [<unknown file> @ <unknown line number>]
00007FFF98AD4F7400007FFF98AD3340 custom_rasterizer_kernel.cp312-win_amd64.pyd!PyInit_custom_rasterizer_kernel [<unknown file> @ <unknown line number>]
00007FFF98AD3E9400007FFF98AD3340 custom_rasterizer_kernel.cp312-win_amd64.pyd!PyInit_custom_rasterizer_kernel [<unknown file> @ <unknown line number>]
00007FFF98AD3F7400007FFF98AD3340 custom_rasterizer_kernel.cp312-win_amd64.pyd!PyInit_custom_rasterizer_kernel [<unknown file> @ <unknown line number>]
00007FFF98ABEB8D00007FFF98AB56B0 custom_rasterizer_kernel.cp312-win_amd64.pyd!c10::ivalue::Object::operator= [<unknown file> @ <unknown line number>]
00007FF8A8E172F800007FF8A8E16C24 python312.dll!PyUnicode_DecodeUTF7Stateful [<unknown file> @ <unknown line number>]
00007FF8A8E46A0200007FF8A8E46380 python312.dll!PyObject_Vectorcall [<unknown file> @ <unknown line number>]
00007FF8A8E463B500007FF8A8E46380 python312.dll!PyObject_Vectorcall [<unknown file> @ <unknown line number>]
00007FF8A8E478AD00007FF8A8E46FE0 python312.dll!PyEval_EvalFrameDefault [<unknown file> @ <unknown line number>]
00007FF8A8E45A2C00007FF8A8E458B0 python312.dll!PyFunction_Vectorcall [<unknown file> @ <unknown line number>]
00007FF8A8E4099C00007FF8A8E40550 python312.dll!PyArg_CheckPositional [<unknown file> @ <unknown line number>]
00007FF8A8EBECCB00007FF8A8EBEB50 python312.dll!PyObject_Call [<unknown file> @ <unknown line number>]
00007FF8A8EBEBBF00007FF8A8EBEB50 python312.dll!PyObject_Call [<unknown file> @ <unknown line number>]
00007FF8A8E4B20D00007FF8A8E46FE0 python312.dll!PyEval_EvalFrameDefault [<unknown file> @ <unknown line number>]
00007FF8A8E45A2C00007FF8A8E458B0 python312.dll!PyFunction_Vectorcall [<unknown file> @ <unknown line number>]
00007FF8A8E409F000007FF8A8E40550 python312.dll!PyArg_CheckPositional [<unknown file> @ <unknown line number>]
00007FF8A8EBEC7500007FF8A8EBEB50 python312.dll!PyObject_Call [<unknown file> @ <unknown line number>]
00007FF8A8EBEBBF00007FF8A8EBEB50 python312.dll!PyObject_Call [<unknown file> @ <unknown line number>]
00007FF8A8E0303400007FF8A8E02F18 python312.dll!PyThreadState_Bind [<unknown file> @ <unknown line number>]
00007FF8A8E0259A00007FF8A8E02390 python312.dll!PyThreadState_Clear [<unknown file> @ <unknown line number>]
00007FF91AB4933300007FF91AB49290 ucrtbase.dll!recalloc [<unknown file> @ <unknown line number>]
00007FF91C63259D00007FF91C632580 KERNEL32.DLL!BaseThreadInitThunk [<unknown file> @ <unknown line number>]
00007FF91D04AF3800007FF91D04AF10 ntdll.dll!RtlUserThreadStart [<unknown file> @ <unknown line number>]

## Stack Trace
```
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 327, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 202, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)

  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Hunyuan3DWrapper\nodes.py", line 501, in process
    normal_maps, masks = self.render_normal_multiview(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Hunyuan3DWrapper\nodes.py", line 538, in render_normal_multiview
    normal_map, mask = self.render.render_normal(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Hunyuan3DWrapper\hy3dgen\texgen\differentiable_renderer\mesh_render.py", line 456, in render_normal
    rast_out, rast_out_db = self.raster_rasterize(
                            ^^^^^^^^^^^^^^^^^^^^^^

  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Hunyuan3DWrapper\hy3dgen\texgen\differentiable_renderer\mesh_render.py", line 184, in raster_rasterize
    findices, barycentric = self.raster.rasterize(pos, tri, resolution)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\custom_rasterizer\render.py", line 31, in rasterize
    findices, barycentric = custom_rasterizer_kernel.rasterize_image(pos[0], tri, clamp_depth, resolution[1],
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

```
## System Information
- **ComfyUI Version:** 0.3.27
- **Arguments:** ComfyUI\main.py --windows-standalone-build
- **OS:** nt
- **Python Version:** 3.12.9 (tags/v3.12.9:fdb8142, Feb  4 2025, 15:27:58) [MSC v.1942 64 bit (AMD64)]
- **Embedded Python:** true
- **PyTorch Version:** 2.6.0+cu126
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 2060 SUPER : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 8589475840
  - **VRAM Free:** 5956516188
  - **Torch VRAM Total:** 1509949440
  - **Torch VRAM Free:** 11090268

## Logs
```
2025-03-23T14:14:37.720957 - [START] Security scan2025-03-23T14:14:37.720957 - 
2025-03-23T14:14:38.571888 - [DONE] Security scan2025-03-23T14:14:38.571888 - 
2025-03-23T14:14:38.677591 - ## ComfyUI-Manager: installing dependencies done.2025-03-23T14:14:38.677591 - 
2025-03-23T14:14:38.677591 - ** ComfyUI startup time:2025-03-23T14:14:38.678593 -  2025-03-23T14:14:38.678593 - 2025-03-23 14:14:38.6772025-03-23T14:14:38.678593 - 
2025-03-23T14:14:38.678593 - ** Platform:2025-03-23T14:14:38.678593 -  2025-03-23T14:14:38.678593 - Windows2025-03-23T14:14:38.678593 - 
2025-03-23T14:14:38.678593 - ** Python version:2025-03-23T14:14:38.678593 -  2025-03-23T14:14:38.678593 - 3.12.9 (tags/v3.12.9:fdb8142, Feb  4 2025, 15:27:58) [MSC v.1942 64 bit (AMD64)]2025-03-23T14:14:38.678593 - 
2025-03-23T14:14:38.678593 - ** Python executable:2025-03-23T14:14:38.678593 -  2025-03-23T14:14:38.678593 - C:\ComfyUI_windows_portable\python_embeded\python.exe2025-03-23T14:14:38.678593 - 
2025-03-23T14:14:38.678593 - ** ComfyUI Path:2025-03-23T14:14:38.678593 -  2025-03-23T14:14:38.678593 - C:\ComfyUI_windows_portable\ComfyUI2025-03-23T14:14:38.678593 - 
2025-03-23T14:14:38.678593 - ** ComfyUI Base Folder Path:2025-03-23T14:14:38.679591 -  2025-03-23T14:14:38.679591 - C:\ComfyUI_windows_portable\ComfyUI2025-03-23T14:14:38.679591 - 
2025-03-23T14:14:38.679591 - ** User directory:2025-03-23T14:14:38.679591 -  2025-03-23T14:14:38.679591 - C:\ComfyUI_windows_portable\ComfyUI\user2025-03-23T14:14:38.679591 - 
2025-03-23T14:14:38.679591 - ** ComfyUI-Manager config path:2025-03-23T14:14:38.679591 -  2025-03-23T14:14:38.679591 - C:\ComfyUI_windows_portable\ComfyUI\user\default\ComfyUI-Manager\config.ini2025-03-23T14:14:38.679591 - 
2025-03-23T14:14:38.679591 - ** Log path:2025-03-23T14:14:38.679591 -  2025-03-23T14:14:38.679591 - C:\ComfyUI_windows_portable\ComfyUI\user\comfyui.log2025-03-23T14:14:38.679591 - 
2025-03-23T14:14:39.753361 - 
Prestartup times for custom nodes:
2025-03-23T14:14:39.753361 -    2.7 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
2025-03-23T14:14:39.753361 - 
2025-03-23T14:14:41.430938 - Checkpoint files will always be loaded safely.
2025-03-23T14:14:41.555731 - Total VRAM 8192 MB, total RAM 32717 MB
2025-03-23T14:14:41.555731 - pytorch version: 2.6.0+cu126
2025-03-23T14:14:41.556735 - Set vram state to: NORMAL_VRAM
2025-03-23T14:14:41.556735 - Device: cuda:0 NVIDIA GeForce RTX 2060 SUPER : cudaMallocAsync
2025-03-23T14:14:42.771032 - Using pytorch attention
2025-03-23T14:14:43.993023 - ComfyUI version: 0.3.27
2025-03-23T14:14:44.030082 - ComfyUI frontend version: 1.14.5
2025-03-23T14:14:44.031594 - [Prompt Server] web root: C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\comfyui_frontend_package\static
2025-03-23T14:14:45.424306 - ### Loading: ComfyUI-Manager (V3.31.7)
2025-03-23T14:14:45.424306 - [ComfyUI-Manager] network_mode: public
2025-03-23T14:14:45.525986 - ### ComfyUI Revision: 3288 [75c1c757] *DETACHED | Released on '2025-03-21'
2025-03-23T14:14:45.782398 - 
Import times for custom nodes:
2025-03-23T14:14:45.783403 -    0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
2025-03-23T14:14:45.783403 -    0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_essentials
2025-03-23T14:14:45.783403 -    0.4 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
2025-03-23T14:14:45.783403 -    0.9 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Hunyuan3DWrapper
2025-03-23T14:14:45.783403 - 
2025-03-23T14:14:45.792914 - Starting server

2025-03-23T14:14:45.792914 - To see the GUI go to: http://127.0.0.1:8188
2025-03-23T14:14:45.842005 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
2025-03-23T14:14:45.844012 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
2025-03-23T14:14:45.860525 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
2025-03-23T14:14:45.897594 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
2025-03-23T14:14:45.934666 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
2025-03-23T14:14:49.148906 - FETCH ComfyRegistry Data: 5/792025-03-23T14:14:49.150412 - 
2025-03-23T14:14:52.842764 - FETCH ComfyRegistry Data: 10/792025-03-23T14:14:52.842764 - 
2025-03-23T14:14:56.498038 - FETCH ComfyRegistry Data: 15/792025-03-23T14:14:56.498038 - 
2025-03-23T14:15:00.618835 - FETCH ComfyRegistry Data: 20/792025-03-23T14:15:00.618835 - 
2025-03-23T14:15:04.454282 - FETCH ComfyRegistry Data: 25/792025-03-23T14:15:04.454282 - 
2025-03-23T14:15:08.050176 - FETCH ComfyRegistry Data: 30/792025-03-23T14:15:08.050176 - 
2025-03-23T14:15:11.843767 - FETCH ComfyRegistry Data: 35/792025-03-23T14:15:11.843767 - 
2025-03-23T14:15:15.495549 - FETCH ComfyRegistry Data: 40/792025-03-23T14:15:15.495549 - 
2025-03-23T14:15:19.332685 - FETCH ComfyRegistry Data: 45/792025-03-23T14:15:19.332685 - 
2025-03-23T14:15:22.963878 - FETCH ComfyRegistry Data: 50/792025-03-23T14:15:22.963878 - 
2025-03-23T14:15:26.551352 - FETCH ComfyRegistry Data: 55/792025-03-23T14:15:26.551352 - 
2025-03-23T14:15:30.211424 - FETCH ComfyRegistry Data: 60/792025-03-23T14:15:30.212429 - 
2025-03-23T14:15:30.235464 - got prompt
2025-03-23T14:15:30.237463 - Failed to validate prompt for output 127:
2025-03-23T14:15:30.237463 - * Hy3DSampleMultiView 88:
2025-03-23T14:15:30.237463 -   - Required input is missing: position_maps
2025-03-23T14:15:30.237463 -   - Required input is missing: normal_maps
2025-03-23T14:15:30.237463 - * Hy3DBakeFromMultiview 92:
2025-03-23T14:15:30.237463 -   - Required input is missing: renderer
2025-03-23T14:15:30.237463 - Output will be ignored
2025-03-23T14:15:30.237463 - Failed to validate prompt for output 126:
2025-03-23T14:15:30.237463 - Output will be ignored
2025-03-23T14:15:30.237463 - Failed to validate prompt for output 125:
2025-03-23T14:15:30.238462 - Output will be ignored
2025-03-23T14:15:30.238462 - Failed to validate prompt for output 111:
2025-03-23T14:15:30.238462 - Output will be ignored
2025-03-23T14:15:30.238462 - Failed to validate prompt for output 99:
2025-03-23T14:15:30.238462 - Output will be ignored
2025-03-23T14:15:30.238462 - Failed to validate prompt for output 154:
2025-03-23T14:15:30.238462 - Output will be ignored
2025-03-23T14:15:31.644671 - 
Loading pipeline components...: 100%|████████████████████████████████████████████████████| 6/6 [00:01<00:00,  3.65it/s]2025-03-23T14:15:31.644671 - 
Loading pipeline components...: 100%|████████████████████████████████████████████████████| 6/6 [00:01<00:00,  4.33it/s]2025-03-23T14:15:31.644671 - 
2025-03-23T14:15:33.650316 - C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\albumentations\__init__.py:13: UserWarning: A new version of Albumentations is available: 2.0.5 (you have 1.4.15). Upgrade using: pip install -U albumentations. To disable automatic update checks, set the environment variable NO_ALBUMENTATIONS_UPDATE to 1.
  check_for_updates()
2025-03-23T14:15:33.729945 - FETCH ComfyRegistry Data: 65/792025-03-23T14:15:33.730953 - 
2025-03-23T14:15:33.835624 - C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\timm\models\layers\__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
2025-03-23T14:15:34.987518 - C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\functional.py:539: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\TensorShape.cpp:3638.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
2025-03-23T14:15:37.212371 - Settings -> Mode=base, Device=cuda:0, Torchscript=enabled2025-03-23T14:15:37.212371 - 
2025-03-23T14:15:38.288512 - FETCH ComfyRegistry Data: 70/792025-03-23T14:15:38.289515 - 
2025-03-23T14:15:39.079844 - C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torchvision\transforms\v2\_deprecated.py:42: UserWarning: The transform `ToTensor()` is deprecated and will be removed in a future release. Instead, please use `v2.Compose([v2.ToImage(), v2.ToDtype(torch.float32, scale=True)])`.Output is equivalent up to float precision.
  warnings.warn(
2025-03-23T14:15:39.140441 - image in shape2025-03-23T14:15:39.140441 -  2025-03-23T14:15:39.140441 - torch.Size([1, 512, 512, 3])2025-03-23T14:15:39.140441 - 
2025-03-23T14:15:41.812772 - 
 42%|██████████████████████████████████▍                                               | 21/50 [00:02<00:02, 12.28it/s]2025-03-23T14:15:41.882385 - FETCH ComfyRegistry Data: 75/792025-03-23T14:15:41.883385 - 
2025-03-23T14:15:43.935446 - 
 98%|████████████████████████████████████████████████████████████████████████████████▎ | 49/50 [00:04<00:00, 13.53it/s]2025-03-23T14:15:44.009565 - 
100%|██████████████████████████████████████████████████████████████████████████████████| 50/50 [00:04<00:00, 11.49it/s]2025-03-23T14:15:44.009565 - 
2025-03-23T14:15:44.928262 - Loading model from C:\ComfyUI_windows_portable\ComfyUI\models\diffusion_models\hunyuan3d-dit-v2-mini-fast.safetensors
2025-03-23T14:15:44.961333 - Model has 16 single blocks, setting config to dit_config_mini.yaml
2025-03-23T14:15:44.965337 - Model has guidance_in, setting guidance_embed to True
2025-03-23T14:15:45.411738 - FETCH ComfyRegistry Data [DONE]2025-03-23T14:15:45.411738 - 
2025-03-23T14:15:45.549503 - [ComfyUI-Manager] default cache updated: https://api.comfy.org/nodes
2025-03-23T14:15:45.568033 - FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json2025-03-23T14:15:45.568033 - 2025-03-23T14:15:45.629645 -  [DONE]2025-03-23T14:15:45.629645 - 
2025-03-23T14:15:45.688243 - [ComfyUI-Manager] All startup tasks have been completed.
2025-03-23T14:15:46.838275 - image shape2025-03-23T14:15:46.838275 -  2025-03-23T14:15:46.838275 - torch.Size([1, 3, 518, 518])2025-03-23T14:15:46.838275 - 
2025-03-23T14:15:47.710166 - guidance: 2025-03-23T14:15:47.711672 -  2025-03-23T14:15:47.722192 - tensor([5.5000], device='cuda:0', dtype=torch.float16)2025-03-23T14:15:47.722192 - 
2025-03-23T14:16:01.348157 - 
Diffusion Sampling:: 100%|█████████████████████████████████████████████████████████████| 50/50 [00:13<00:00,  3.67it/s]2025-03-23T14:16:01.349661 - 
Diffusion Sampling:: 100%|█████████████████████████████████████████████████████████████| 50/50 [00:13<00:00,  3.67it/s]2025-03-23T14:16:01.349661 - 
2025-03-23T14:16:01.349661 - latents shape: 2025-03-23T14:16:01.349661 -  2025-03-23T14:16:01.349661 - torch.Size([1, 3072, 64])2025-03-23T14:16:01.349661 - 
2025-03-23T14:16:01.350667 - Allocated memory: memory=1.400 GB
2025-03-23T14:16:01.350667 - Max allocated memory: max_memory=3.585 GB
2025-03-23T14:16:01.350667 - Max reserved memory: max_reserved=3.625 GB
2025-03-23T14:16:02.403043 - 
FlashVDM Volume Decoding: 100%|███████████████████████████████████████████████████████| 32/32 [00:00<00:00, 240.11it/s]2025-03-23T14:16:02.404045 - 
FlashVDM Volume Decoding: 100%|███████████████████████████████████████████████████████| 32/32 [00:00<00:00, 240.11it/s]2025-03-23T14:16:02.404045 - 
2025-03-23T14:16:05.370319 - MC Surface Extractor2025-03-23T14:16:05.371320 - 
2025-03-23T14:16:07.671343 - Decoded mesh with 254129 vertices and 830178 faces
2025-03-23T14:16:08.357075 - Removed floaters, resulting in 254129 vertices and 508466 faces
2025-03-23T14:16:08.931657 - Removed degenerate faces, resulting in 254129 vertices and 508466 faces
2025-03-23T14:16:16.777426 - Reduced faces, resulting in 24896 vertices and 50000 faces
2025-03-23T14:16:16.783941 - Prompt executed in 46.54 seconds
2025-03-23T14:16:59.900539 - got prompt
2025-03-23T14:16:59.902547 - Failed to validate prompt for output 127:
2025-03-23T14:16:59.903548 - * Hy3DSampleMultiView 88:
2025-03-23T14:16:59.903548 -   - Required input is missing: position_maps
2025-03-23T14:16:59.903548 -   - Required input is missing: normal_maps
2025-03-23T14:16:59.903548 - * Hy3DBakeFromMultiview 92:
2025-03-23T14:16:59.903548 -   - Required input is missing: renderer
2025-03-23T14:16:59.904547 - Output will be ignored
2025-03-23T14:16:59.904547 - Failed to validate prompt for output 126:
2025-03-23T14:16:59.904547 - Output will be ignored
2025-03-23T14:16:59.904547 - Failed to validate prompt for output 125:
2025-03-23T14:16:59.904547 - Output will be ignored
2025-03-23T14:16:59.904547 - Failed to validate prompt for output 111:
2025-03-23T14:16:59.905546 - Output will be ignored
2025-03-23T14:16:59.905546 - Failed to validate prompt for output 99:
2025-03-23T14:16:59.905546 - Output will be ignored
2025-03-23T14:16:59.905546 - Failed to validate prompt for output 154:
2025-03-23T14:16:59.905546 - Output will be ignored
2025-03-23T14:17:04.770179 - C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torchvision\transforms\v2\_deprecated.py:42: UserWarning: The transform `ToTensor()` is deprecated and will be removed in a future release. Instead, please use `v2.Compose([v2.ToImage(), v2.ToDtype(torch.float32, scale=True)])`.Output is equivalent up to float precision.
  warnings.warn(
2025-03-23T14:17:04.796216 - image in shape2025-03-23T14:17:04.796216 -  2025-03-23T14:17:04.796216 - torch.Size([1, 512, 512, 3])2025-03-23T14:17:04.796216 - 
2025-03-23T14:17:09.560615 - 
 98%|████████████████████████████████████████████████████████████████████████████████▎ | 49/50 [00:04<00:00, 11.71it/s]2025-03-23T14:17:09.644246 - 
100%|██████████████████████████████████████████████████████████████████████████████████| 50/50 [00:04<00:00, 10.96it/s]2025-03-23T14:17:09.644246 - 
2025-03-23T14:17:11.057314 - image shape2025-03-23T14:17:11.057314 -  2025-03-23T14:17:11.057314 - torch.Size([1, 3, 518, 518])2025-03-23T14:17:11.057314 - 
2025-03-23T14:17:11.545843 - guidance: 2025-03-23T14:17:11.545843 -  2025-03-23T14:17:11.547843 - tensor([5.5000], device='cuda:0', dtype=torch.float16)2025-03-23T14:17:11.547843 - 
2025-03-23T14:17:25.561084 - 
Diffusion Sampling:: 100%|█████████████████████████████████████████████████████████████| 50/50 [00:14<00:00,  3.56it/s]2025-03-23T14:17:25.561084 - 
Diffusion Sampling:: 100%|█████████████████████████████████████████████████████████████| 50/50 [00:14<00:00,  3.57it/s]2025-03-23T14:17:25.561084 - 
2025-03-23T14:17:25.561084 - latents shape: 2025-03-23T14:17:25.561084 -  2025-03-23T14:17:25.561084 - torch.Size([1, 3072, 64])2025-03-23T14:17:25.561084 - 
2025-03-23T14:17:25.562657 - Allocated memory: memory=1.400 GB
2025-03-23T14:17:25.562657 - Max allocated memory: max_memory=3.585 GB
2025-03-23T14:17:25.562657 - Max reserved memory: max_reserved=3.625 GB
2025-03-23T14:17:26.074403 - 
FlashVDM Volume Decoding: 100%|███████████████████████████████████████████████████████| 32/32 [00:00<00:00, 273.01it/s]2025-03-23T14:17:26.074403 - 
FlashVDM Volume Decoding: 100%|███████████████████████████████████████████████████████| 32/32 [00:00<00:00, 273.01it/s]2025-03-23T14:17:26.074403 - 
2025-03-23T14:17:28.159488 - MC Surface Extractor2025-03-23T14:17:28.159488 - 
2025-03-23T14:17:29.939900 - Decoded mesh with 120896 vertices and 407144 faces
2025-03-23T14:17:30.348588 - Removed floaters, resulting in 120896 vertices and 241792 faces
2025-03-23T14:17:30.699277 - Removed degenerate faces, resulting in 120896 vertices and 241792 faces
2025-03-23T14:17:33.814305 - Reduced faces, resulting in 25000 vertices and 50000 faces
2025-03-23T14:17:33.820817 - Prompt executed in 33.91 seconds
2025-03-23T14:19:08.065618 - got prompt
2025-03-23T14:19:10.047575 - C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torchvision\transforms\v2\_deprecated.py:42: UserWarning: The transform `ToTensor()` is deprecated and will be removed in a future release. Instead, please use `v2.Compose([v2.ToImage(), v2.ToDtype(torch.float32, scale=True)])`.Output is equivalent up to float precision.
  warnings.warn(
2025-03-23T14:19:10.072627 - image in shape2025-03-23T14:19:10.072627 -  2025-03-23T14:19:10.072627 - torch.Size([1, 512, 512, 3])2025-03-23T14:19:10.072627 - 
2025-03-23T14:19:14.827430 - 
 98%|████████████████████████████████████████████████████████████████████████████████▎ | 49/50 [00:04<00:00, 12.16it/s]2025-03-23T14:19:14.911066 - 
100%|██████████████████████████████████████████████████████████████████████████████████| 50/50 [00:04<00:00, 10.92it/s]2025-03-23T14:19:14.911066 - 
2025-03-23T14:19:16.337367 - image shape2025-03-23T14:19:16.337367 -  2025-03-23T14:19:16.337367 - torch.Size([1, 3, 518, 518])2025-03-23T14:19:16.337367 - 
2025-03-23T14:19:16.793590 - guidance: 2025-03-23T14:19:16.793590 -  2025-03-23T14:19:16.794589 - tensor([5.5000], device='cuda:0', dtype=torch.float16)2025-03-23T14:19:16.794589 - 
2025-03-23T14:19:30.575652 - 
Diffusion Sampling:: 100%|█████████████████████████████████████████████████████████████| 50/50 [00:13<00:00,  3.52it/s]2025-03-23T14:19:30.577156 - 
Diffusion Sampling:: 100%|█████████████████████████████████████████████████████████████| 50/50 [00:13<00:00,  3.63it/s]2025-03-23T14:19:30.577156 - 
2025-03-23T14:19:30.577156 - latents shape: 2025-03-23T14:19:30.577156 -  2025-03-23T14:19:30.577156 - torch.Size([1, 3072, 64])2025-03-23T14:19:30.577156 - 
2025-03-23T14:19:30.578161 - Allocated memory: memory=1.400 GB
2025-03-23T14:19:30.578161 - Max allocated memory: max_memory=3.585 GB
2025-03-23T14:19:30.578161 - Max reserved memory: max_reserved=3.625 GB
2025-03-23T14:19:31.131641 - 
FlashVDM Volume Decoding: 100%|███████████████████████████████████████████████████████| 32/32 [00:00<00:00, 257.57it/s]2025-03-23T14:19:31.131641 - 
FlashVDM Volume Decoding: 100%|███████████████████████████████████████████████████████| 32/32 [00:00<00:00, 257.57it/s]2025-03-23T14:19:31.131641 - 
2025-03-23T14:19:39.307413 - MC Surface Extractor2025-03-23T14:19:39.308366 - 
2025-03-23T14:19:43.707292 - Decoded mesh with 1406454 vertices and 2817978 faces
2025-03-23T14:19:47.834478 - Removed floaters, resulting in 1405392 vertices and 2811696 faces
2025-03-23T14:19:51.217793 - Removed degenerate faces, resulting in 1405392 vertices and 2811696 faces
2025-03-23T14:20:39.551122 - Reduced faces, resulting in 24544 vertices and 50000 faces
2025-03-23T14:20:51.755335 - camera_distance: 1.452025-03-23T14:20:51.755335 - 
2025-03-23T14:20:52.417924 - !!! Exception during processing !!! CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Exception raised from c10_cuda_check_implementation at C:\actions-runner\_work\pytorch\pytorch\pytorch\c10\cuda\CUDAException.cpp:43 (most recent call first):
00007FF8D50091D900007FF8D5009130 c10.dll!c10::Error::Error [<unknown file> @ <unknown line number>]
00007FF8D5007A6A00007FF8D5007A10 c10.dll!c10::detail::torchCheckFail [<unknown file> @ <unknown line number>]
00007FF8E1D94E3F00007FF8E1D94B40 c10_cuda.dll!c10::cuda::c10_cuda_check_implementation [<unknown file> @ <unknown line number>]
00007FF8E1D9B10300007FF8E1D961F0 c10_cuda.dll!c10::cuda::warn_or_error_on_sync [<unknown file> @ <unknown line number>]
00007FF8E1D9638D00007FF8E1D961F0 c10_cuda.dll!c10::cuda::warn_or_error_on_sync [<unknown file> @ <unknown line number>]
00007FF8D4FCAAA300007FF8D4FCAA40 c10.dll!c10::StorageImpl::StorageImpl [<unknown file> @ <unknown line number>]
00007FFFE58E5A7F00007FFFE58E5340 torch_cpu.dll!at::DynamicLibrary::sym [<unknown file> @ <unknown line number>]
00007FFFE58E7DEE00007FFFE58E7DC0 torch_cpu.dll!at::detail::empty_generic [<unknown file> @ <unknown line number>]
00007FFFA829657500007FFFA8296490 torch_cuda.dll!at::detail::empty_cuda [<unknown file> @ <unknown line number>]
00007FFFA829646E00007FFFA82963B0 torch_cuda.dll!at::detail::empty_cuda [<unknown file> @ <unknown line number>]
00007FFFA83A5C7800007FFFA83A5C10 torch_cuda.dll!at::native::empty_cuda [<unknown file> @ <unknown line number>]
00007FFFAA0B803E00007FFFAA05CCF0 torch_cuda.dll!at::cuda::where_outf [<unknown file> @ <unknown line number>]
00007FFFA9FA653E00007FFFA9F374E0 torch_cuda.dll!at::cuda::bucketize_outf [<unknown file> @ <unknown line number>]
00007FFFE64A362C00007FFFE648C070 torch_cpu.dll!at::_ops::xlogy__Tensor::redispatch [<unknown file> @ <unknown line number>]
00007FFFE6513C9100007FFFE648C070 torch_cpu.dll!at::_ops::xlogy__Tensor::redispatch [<unknown file> @ <unknown line number>]
00007FFFE65EE1AE00007FFFE65EE0D0 torch_cpu.dll!at::_ops::empty_memory_format::redispatch [<unknown file> @ <unknown line number>]
00007FFFE686C64900007FFFE68492D0 torch_cpu.dll!at::_ops::view_as_real::redispatch [<unknown file> @ <unknown line number>]
00007FFFE686A56E00007FFFE68492D0 torch_cpu.dll!at::_ops::view_as_real::redispatch [<unknown file> @ <unknown line number>]
00007FFFE64A362C00007FFFE648C070 torch_cpu.dll!at::_ops::xlogy__Tensor::redispatch [<unknown file> @ <unknown line number>]
00007FFFE655B6B800007FFFE655B470 torch_cpu.dll!at::_ops::empty_memory_format::call [<unknown file> @ <unknown line number>]
00007FFFE5A1DD7900007FFFE59FEF10 torch_cpu.dll!at::functorch::reshape_dim_outof_symint [<unknown file> @ <unknown line number>]
00007FFFE5E4B3B600007FFFE5E4B2B0 torch_cpu.dll!at::native::zeros_symint [<unknown file> @ <unknown line number>]
00007FFFE6AE297A00007FFFE6ADB5F0 torch_cpu.dll!at::compositeexplicitautograd::view_copy_symint_outf [<unknown file> @ <unknown line number>]
00007FFFE6AB04FB00007FFFE6A663B0 torch_cpu.dll!at::compositeexplicitautograd::bucketize_outf [<unknown file> @ <unknown line number>]
00007FFFE631E2E500007FFFE631E210 torch_cpu.dll!at::_ops::zeros::redispatch [<unknown file> @ <unknown line number>]
00007FFFE6870B0C00007FFFE68492D0 torch_cpu.dll!at::_ops::view_as_real::redispatch [<unknown file> @ <unknown line number>]
00007FFFE686A44B00007FFFE68492D0 torch_cpu.dll!at::_ops::view_as_real::redispatch [<unknown file> @ <unknown line number>]
00007FFFE62B3A1000007FFFE62B3810 torch_cpu.dll!at::_ops::zeros::call [<unknown file> @ <unknown line number>]
00007FFF98AB5B8D00007FFF98AB56B0 custom_rasterizer_kernel.cp312-win_amd64.pyd!c10::ivalue::Object::operator= [<unknown file> @ <unknown line number>]
00007FFF98AD675E00007FFF98AD3340 custom_rasterizer_kernel.cp312-win_amd64.pyd!PyInit_custom_rasterizer_kernel [<unknown file> @ <unknown line number>]
00007FFF98AD32FD00007FFF98AB56B0 custom_rasterizer_kernel.cp312-win_amd64.pyd!c10::ivalue::Object::operator= [<unknown file> @ <unknown line number>]
00007FFF98AD4F7400007FFF98AD3340 custom_rasterizer_kernel.cp312-win_amd64.pyd!PyInit_custom_rasterizer_kernel [<unknown file> @ <unknown line number>]
00007FFF98AD3E9400007FFF98AD3340 custom_rasterizer_kernel.cp312-win_amd64.pyd!PyInit_custom_rasterizer_kernel [<unknown file> @ <unknown line number>]
00007FFF98AD3F7400007FFF98AD3340 custom_rasterizer_kernel.cp312-win_amd64.pyd!PyInit_custom_rasterizer_kernel [<unknown file> @ <unknown line number>]
00007FFF98ABEB8D00007FFF98AB56B0 custom_rasterizer_kernel.cp312-win_amd64.pyd!c10::ivalue::Object::operator= [<unknown file> @ <unknown line number>]
00007FF8A8E172F800007FF8A8E16C24 python312.dll!PyUnicode_DecodeUTF7Stateful [<unknown file> @ <unknown line number>]
00007FF8A8E46A0200007FF8A8E46380 python312.dll!PyObject_Vectorcall [<unknown file> @ <unknown line number>]
00007FF8A8E463B500007FF8A8E46380 python312.dll!PyObject_Vectorcall [<unknown file> @ <unknown line number>]
00007FF8A8E478AD00007FF8A8E46FE0 python312.dll!PyEval_EvalFrameDefault [<unknown file> @ <unknown line number>]
00007FF8A8E45A2C00007FF8A8E458B0 python312.dll!PyFunction_Vectorcall [<unknown file> @ <unknown line number>]
00007FF8A8E4099C00007FF8A8E40550 python312.dll!PyArg_CheckPositional [<unknown file> @ <unknown line number>]
00007FF8A8EBECCB00007FF8A8EBEB50 python312.dll!PyObject_Call [<unknown file> @ <unknown line number>]
00007FF8A8EBEBBF00007FF8A8EBEB50 python312.dll!PyObject_Call [<unknown file> @ <unknown line number>]
00007FF8A8E4B20D00007FF8A8E46FE0 python312.dll!PyEval_EvalFrameDefault [<unknown file> @ <unknown line number>]
00007FF8A8E45A2C00007FF8A8E458B0 python312.dll!PyFunction_Vectorcall [<unknown file> @ <unknown line number>]
00007FF8A8E409F000007FF8A8E40550 python312.dll!PyArg_CheckPositional [<unknown file> @ <unknown line number>]
00007FF8A8EBEC7500007FF8A8EBEB50 python312.dll!PyObject_Call [<unknown file> @ <unknown line number>]
00007FF8A8EBEBBF00007FF8A8EBEB50 python312.dll!PyObject_Call [<unknown file> @ <unknown line number>]
00007FF8A8E0303400007FF8A8E02F18 python312.dll!PyThreadState_Bind [<unknown file> @ <unknown line number>]
00007FF8A8E0259A00007FF8A8E02390 python312.dll!PyThreadState_Clear [<unknown file> @ <unknown line number>]
00007FF91AB4933300007FF91AB49290 ucrtbase.dll!recalloc [<unknown file> @ <unknown line number>]
00007FF91C63259D00007FF91C632580 KERNEL32.DLL!BaseThreadInitThunk [<unknown file> @ <unknown line number>]
00007FF91D04AF3800007FF91D04AF10 ntdll.dll!RtlUserThreadStart [<unknown file> @ <unknown line number>]

2025-03-23T14:20:52.420929 - Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 327, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 202, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Hunyuan3DWrapper\nodes.py", line 501, in process
    normal_maps, masks = self.render_normal_multiview(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Hunyuan3DWrapper\nodes.py", line 538, in render_normal_multiview
    normal_map, mask = self.render.render_normal(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Hunyuan3DWrapper\hy3dgen\texgen\differentiable_renderer\mesh_render.py", line 456, in render_normal
    rast_out, rast_out_db = self.raster_rasterize(
                            ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Hunyuan3DWrapper\hy3dgen\texgen\differentiable_renderer\mesh_render.py", line 184, in raster_rasterize
    findices, barycentric = self.raster.rasterize(pos, tri, resolution)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\custom_rasterizer\render.py", line 31, in rasterize
    findices, barycentric = custom_rasterizer_kernel.rasterize_image(pos[0], tri, clamp_depth, resolution[1],
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Exception raised from c10_cuda_check_implementation at C:\actions-runner\_work\pytorch\pytorch\pytorch\c10\cuda\CUDAException.cpp:43 (most recent call first):
00007FF8D50091D900007FF8D5009130 c10.dll!c10::Error::Error [<unknown file> @ <unknown line number>]
00007FF8D5007A6A00007FF8D5007A10 c10.dll!c10::detail::torchCheckFail [<unknown file> @ <unknown line number>]
00007FF8E1D94E3F00007FF8E1D94B40 c10_cuda.dll!c10::cuda::c10_cuda_check_implementation [<unknown file> @ <unknown line number>]
00007FF8E1D9B10300007FF8E1D961F0 c10_cuda.dll!c10::cuda::warn_or_error_on_sync [<unknown file> @ <unknown line number>]
00007FF8E1D9638D00007FF8E1D961F0 c10_cuda.dll!c10::cuda::warn_or_error_on_sync [<unknown file> @ <unknown line number>]
00007FF8D4FCAAA300007FF8D4FCAA40 c10.dll!c10::StorageImpl::StorageImpl [<unknown file> @ <unknown line number>]
00007FFFE58E5A7F00007FFFE58E5340 torch_cpu.dll!at::DynamicLibrary::sym [<unknown file> @ <unknown line number>]
00007FFFE58E7DEE00007FFFE58E7DC0 torch_cpu.dll!at::detail::empty_generic [<unknown file> @ <unknown line number>]
00007FFFA829657500007FFFA8296490 torch_cuda.dll!at::detail::empty_cuda [<unknown file> @ <unknown line number>]
00007FFFA829646E00007FFFA82963B0 torch_cuda.dll!at::detail::empty_cuda [<unknown file> @ <unknown line number>]
00007FFFA83A5C7800007FFFA83A5C10 torch_cuda.dll!at::native::empty_cuda [<unknown file> @ <unknown line number>]
00007FFFAA0B803E00007FFFAA05CCF0 torch_cuda.dll!at::cuda::where_outf [<unknown file> @ <unknown line number>]
00007FFFA9FA653E00007FFFA9F374E0 torch_cuda.dll!at::cuda::bucketize_outf [<unknown file> @ <unknown line number>]
00007FFFE64A362C00007FFFE648C070 torch_cpu.dll!at::_ops::xlogy__Tensor::redispatch [<unknown file> @ <unknown line number>]
00007FFFE6513C9100007FFFE648C070 torch_cpu.dll!at::_ops::xlogy__Tensor::redispatch [<unknown file> @ <unknown line number>]
00007FFFE65EE1AE00007FFFE65EE0D0 torch_cpu.dll!at::_ops::empty_memory_format::redispatch [<unknown file> @ <unknown line number>]
00007FFFE686C64900007FFFE68492D0 torch_cpu.dll!at::_ops::view_as_real::redispatch [<unknown file> @ <unknown line number>]
00007FFFE686A56E00007FFFE68492D0 torch_cpu.dll!at::_ops::view_as_real::redispatch [<unknown file> @ <unknown line number>]
00007FFFE64A362C00007FFFE648C070 torch_cpu.dll!at::_ops::xlogy__Tensor::redispatch [<unknown file> @ <unknown line number>]
00007FFFE655B6B800007FFFE655B470 torch_cpu.dll!at::_ops::empty_memory_format::call [<unknown file> @ <unknown line number>]
00007FFFE5A1DD7900007FFFE59FEF10 torch_cpu.dll!at::functorch::reshape_dim_outof_symint [<unknown file> @ <unknown line number>]
00007FFFE5E4B3B600007FFFE5E4B2B0 torch_cpu.dll!at::native::zeros_symint [<unknown file> @ <unknown line number>]
00007FFFE6AE297A00007FFFE6ADB5F0 torch_cpu.dll!at::compositeexplicitautograd::view_copy_symint_outf [<unknown file> @ <unknown line number>]
00007FFFE6AB04FB00007FFFE6A663B0 torch_cpu.dll!at::compositeexplicitautograd::bucketize_outf [<unknown file> @ <unknown line number>]
00007FFFE631E2E500007FFFE631E210 torch_cpu.dll!at::_ops::zeros::redispatch [<unknown file> @ <unknown line number>]
00007FFFE6870B0C00007FFFE68492D0 torch_cpu.dll!at::_ops::view_as_real::redispatch [<unknown file> @ <unknown line number>]
00007FFFE686A44B00007FFFE68492D0 torch_cpu.dll!at::_ops::view_as_real::redispatch [<unknown file> @ <unknown line number>]
00007FFFE62B3A1000007FFFE62B3810 torch_cpu.dll!at::_ops::zeros::call [<unknown file> @ <unknown line number>]
00007FFF98AB5B8D00007FFF98AB56B0 custom_rasterizer_kernel.cp312-win_amd64.pyd!c10::ivalue::Object::operator= [<unknown file> @ <unknown line number>]
00007FFF98AD675E00007FFF98AD3340 custom_rasterizer_kernel.cp312-win_amd64.pyd!PyInit_custom_rasterizer_kernel [<unknown file> @ <unknown line number>]
00007FFF98AD32FD00007FFF98AB56B0 custom_rasterizer_kernel.cp312-win_amd64.pyd!c10::ivalue::Object::operator= [<unknown file> @ <unknown line number>]
00007FFF98AD4F7400007FFF98AD3340 custom_rasterizer_kernel.cp312-win_amd64.pyd!PyInit_custom_rasterizer_kernel [<unknown file> @ <unknown line number>]
00007FFF98AD3E9400007FFF98AD3340 custom_rasterizer_kernel.cp312-win_amd64.pyd!PyInit_custom_rasterizer_kernel [<unknown file> @ <unknown line number>]
00007FFF98AD3F7400007FFF98AD3340 custom_rasterizer_kernel.cp312-win_amd64.pyd!PyInit_custom_rasterizer_kernel [<unknown file> @ <unknown line number>]
00007FFF98ABEB8D00007FFF98AB56B0 custom_rasterizer_kernel.cp312-win_amd64.pyd!c10::ivalue::Object::operator= [<unknown file> @ <unknown line number>]
00007FF8A8E172F800007FF8A8E16C24 python312.dll!PyUnicode_DecodeUTF7Stateful [<unknown file> @ <unknown line number>]
00007FF8A8E46A0200007FF8A8E46380 python312.dll!PyObject_Vectorcall [<unknown file> @ <unknown line number>]
00007FF8A8E463B500007FF8A8E46380 python312.dll!PyObject_Vectorcall [<unknown file> @ <unknown line number>]
00007FF8A8E478AD00007FF8A8E46FE0 python312.dll!PyEval_EvalFrameDefault [<unknown file> @ <unknown line number>]
00007FF8A8E45A2C00007FF8A8E458B0 python312.dll!PyFunction_Vectorcall [<unknown file> @ <unknown line number>]
00007FF8A8E4099C00007FF8A8E40550 python312.dll!PyArg_CheckPositional [<unknown file> @ <unknown line number>]
00007FF8A8EBECCB00007FF8A8EBEB50 python312.dll!PyObject_Call [<unknown file> @ <unknown line number>]
00007FF8A8EBEBBF00007FF8A8EBEB50 python312.dll!PyObject_Call [<unknown file> @ <unknown line number>]
00007FF8A8E4B20D00007FF8A8E46FE0 python312.dll!PyEval_EvalFrameDefault [<unknown file> @ <unknown line number>]
00007FF8A8E45A2C00007FF8A8E458B0 python312.dll!PyFunction_Vectorcall [<unknown file> @ <unknown line number>]
00007FF8A8E409F000007FF8A8E40550 python312.dll!PyArg_CheckPositional [<unknown file> @ <unknown line number>]
00007FF8A8EBEC7500007FF8A8EBEB50 python312.dll!PyObject_Call [<unknown file> @ <unknown line number>]
00007FF8A8EBEBBF00007FF8A8EBEB50 python312.dll!PyObject_Call [<unknown file> @ <unknown line number>]
00007FF8A8E0303400007FF8A8E02F18 python312.dll!PyThreadState_Bind [<unknown file> @ <unknown line number>]
00007FF8A8E0259A00007FF8A8E02390 python312.dll!PyThreadState_Clear [<unknown file> @ <unknown line number>]
00007FF91AB4933300007FF91AB49290 ucrtbase.dll!recalloc [<unknown file> @ <unknown line number>]
00007FF91C63259D00007FF91C632580 KERNEL32.DLL!BaseThreadInitThunk [<unknown file> @ <unknown line number>]
00007FF91D04AF3800007FF91D04AF10 ntdll.dll!RtlUserThreadStart [<unknown file> @ <unknown line number>]


2025-03-23T14:20:52.421931 - Prompt executed in 104.35 seconds

```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
Workflow too large. Please manually upload the workflow from local file system.
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)

**Comment by jeickholt** [comment]
I have this same error

**Comment by mrabet** [comment]
I did find the problèm, i installed the Last nvidia driver wich it comes with cuda 2.8, but i do have pytorch 2.6.0 with cuda toolkit 2.6.0 installed before. So i uninstall pytorch, and reinstalled the 2.8.0 night version, and everything is ok right now . Hope it helped you all

**Comment by tetsuoo-online** [comment]
> I did find the problèm, i installed the Last nvidia driver wich it comes with cuda 2.8, but i do have pytorch 2.6.0 with cuda toolkit 2.6.0 installed before. So i uninstall pytorch, and reinstalled the 2.8.0 night version, and everything is ok right now . Hope it helped you all

Interesting, but it's unclear do you mean you had Cuda 12.6 (not 2.6.0), then you installed Nightly Cuda 12.8 ? I always struggle with those things, I'm going to try that anyway because I have the same error as you

![Image](https://github.com/user-attachments/assets/c59ee18c-6423-441e-a727-ec54e461f177)

**Comment by mrabet** [comment]
Yeah , it's the same error. I had cuda 12.6 + pytorch 2.6.0 , but when i update my nvidia card driver , the cuda 12.8 was installed with . So to make it work you must have the same version of cuda and torch , so i installed pytorch 2.8.0 night version. Everything is ok now , no more errors even with another nodes

**Comment by tetsuoo-online** [comment]
> Yeah , it's the same error. I had cuda 12.6 + pytorch 2.6.0 , but when i update my nvidia card driver , the cuda 12.8 was installed with . So to make it work you must have the same version of cuda and torch , so i installed pytorch 2.8.0 night version. Everything is ok now , no more errors even with another nodes

It was still unclear as you say installing a new driver will also install Cuda, I didn't have that option. But if I install Cuda Toolkit then it will try to install the driver too. Anyway after a lot of struggles I now have Cuda 12.8+pytorch 2.8 nightly.
IT STILL DOESN'T WORK ! It's been 3 days I'm on this, I give up. No texture for me, fine. That's it x)

**Comment by TopsysLastCigarette** [comment]
> > Yeah , it's the same error. I had cuda 12.6 + pytorch 2.6.0 , but when i update my nvidia card driver , the cuda 12.8 was installed with . So to make it work you must have the same version of cuda and torch , so i installed pytorch 2.8.0 night version. Everything is ok now , no more errors even with another nodes
> 
> It was still unclear as you say installing a new driver will also install Cuda, I didn't have that option. But if I install Cuda Toolkit then it will try to install the driver too. Anyway after a lot of struggles I now have Cuda 12.8+pytorch 2.8 nightly. IT STILL DOESN'T WORK ! It's been 3 days I'm on this, I give up. No texture for me, fine. That's it x)

Hi, I got exactly the same problem as you and I also update the pytorch 2.8 + cuda 12.8 but still got the error. Same as you. 

Now I fixed the problem , let me explain to you, I think it's related to the wheel we installed (custom_rasterizer) 

First, you can keep pytorch 2.8 and cuda 12.8 (no need to reverse) 

after, you'll need to reinstall the wheel but not the one given , this [ONE ](https://drive.google.com/file/d/1twmIqzqjspovGfFUYzVoz9kPIT62GJRo/view?usp=drive_link)(from this [dude original fix](https://github.com/kijai/ComfyUI-Hunyuan3DWrapper/issues/47#issuecomment-2636352445) )

So DL the new wheel, replace the old one in the **_ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Hunyuan3DWrapper\wheels_**

Then reinstall it (guess you're using portable version) so : python_embeded\python.exe -m pip install ComfyUI\custom_nodes\ComfyUI-Hunyuan3DWrapper\wheels\custom_rasterizer-0.1-cp312-cp312-win_amd64.whl 

Hope it helps, GL

**Comment by tetsuoo-online** [comment]
> Hi, I got exactly the same problem as you and I also update the pytorch 2.8 + cuda 12.8 but still got the error. Same as you.
> 
> Now I fixed the problem , let me explain to you, I think it's related to the wheel we installed (custom_rasterizer)
> 
> First, you can keep pytorch 2.8 and cuda 12.8 (no need to reverse)
> 
> after, you'll need to reinstall the wheel but not the one given , this [ONE ](https://drive.google.com/file/d/1twmIqzqjspovGfFUYzVoz9kPIT62GJRo/view?usp=drive_link)(from this [dude original fix](https://github.com/kijai/ComfyUI-Hunyuan3DWrapper/issues/47#issuecomment-2636352445) )
> 
> So DL the new wheel, replace the old one in the **_ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Hunyuan3DWrapper\wheels_**
> 
> Then reinstall it (guess you're using portable version) so : python_embeded\python.exe -m pip install ComfyUI\custom_nodes\ComfyUI-Hunyuan3DWrapper\wheels\custom_rasterizer-0.1-cp312-cp312-win_amd64.whl
> 
> Hope it helps, GL

OMG IT WORKS !!! THANK YOU HERO I was failing on this for so long I couldn't believe it lol thanks

**Comment by usefulslug** [comment]
Cheers, this worked for me too! 

> > > Yeah , it's the same error. I had cuda 12.6 + pytorch 2.6.0 , but when i update my nvidia card driver , the cuda 12.8 was installed with . So to make it work you must have the same version of cuda and torch , so i installed pytorch 2.8.0 night version. Everything is ok now , no more errors even with another nodes
> > 
> > 
> > It was still unclear as you say installing a new driver will also install Cuda, I didn't have that option. But if I install Cuda Toolkit then it will try to install the driver too. Anyway after a lot of struggles I now have Cuda 12.8+pytorch 2.8 nightly. IT STILL DOESN'T WORK ! It's been 3 days I'm on this, I give up. No texture for me, fine. That's it x)
> 
> Hi, I got exactly the same problem as you and I also update the pytorch 2.8 + cuda 12.8 but still got the error. Same as you.
> 
> Now I fixed the problem , let me explain to you, I think it's related to the wheel we installed (custom_rasterizer)
> 
> First, you can keep pytorch 2.8 and cuda 12.8 (no need to reverse)
> 
> after, you'll need to reinstall the wheel but not the one given , this [ONE ](https://drive.google.com/file/d/1twmIqzqjspovGfFUYzVoz9kPIT62GJRo/view?usp=drive_link)(from this [dude original fix](https://github.com/kijai/ComfyUI-Hunyuan3DWrapper/issues/47#issuecomment-2636352445) )
> 
> So DL the new wheel, replace the old one in the **_ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Hunyuan3DWrapper\wheels_**
> 
> Then reinstall it (guess you're using portable version) so : python_embeded\python.exe -m pip install ComfyUI\custom_nodes\ComfyUI-Hunyuan3DWrapper\wheels\custom_rasterizer-0.1-cp312-cp312-win_amd64.whl
> 
> Hope it helps, GL

**Comment by dddffd123** [comment]
> > > Yeah , it's the same error. I had cuda 12.6 + pytorch 2.6.0 , but when i update my nvidia card driver , the cuda 12.8 was installed with . So to make it work you must have the same version of cuda and torch , so i installed pytorch 2.8.0 night version. Everything is ok now , no more errors even with another nodes
> > 
> > 
> > It was still unclear as you say installing a new driver will also install Cuda, I didn't have that option. But if I install Cuda Toolkit then it will try to install the driver too. Anyway after a lot of struggles I now have Cuda 12.8+pytorch 2.8 nightly. IT STILL DOESN'T WORK ! It's been 3 days I'm on this, I give up. No texture for me, fine. That's it x)
> 
> Hi, I got exactly the same problem as you and I also update the pytorch 2.8 + cuda 12.8 but still got the error. Same as you.
> 
> Now I fixed the problem , let me explain to you, I think it's related to the wheel we installed (custom_rasterizer)
> 
> First, you can keep pytorch 2.8 and cuda 12.8 (no need to reverse)
> 
> after, you'll need to reinstall the wheel but not the one given , this [ONE ](https://drive.google.com/file/d/1twmIqzqjspovGfFUYzVoz9kPIT62GJRo/view?usp=drive_link)(from this [dude original fix](https://github.com/kijai/ComfyUI-Hunyuan3DWrapper/issues/47#issuecomment-2636352445) )
> 
> So DL the new wheel, replace the old one in the **_ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Hunyuan3DWrapper\wheels_**
> 
> Then reinstall it (guess you're using portable version) so : python_embeded\python.exe -m pip install ComfyUI\custom_nodes\ComfyUI-Hunyuan3DWrapper\wheels\custom_rasterizer-0.1-cp312-cp312-win_amd64.whl
> 
> Hope it helps, GL

thank. this works for me. I LOVE YOU THANK YOU.

**Comment by tonynoce** [comment]
Can confirm the solution here worked !

**Comment by darkssektor** [comment]
> > > Yeah , it's the same error. I had cuda 12.6 + pytorch 2.6.0 , but when i update my nvidia card driver , the cuda 12.8 was installed with . So to make it work you must have the same version of cuda and torch , so i installed pytorch 2.8.0 night version. Everything is ok now , no more errors even with another nodes
> > 
> > 
> > It was still unclear as you say installing a new driver will also install Cuda, I didn't have that option. But if I install Cuda Toolkit then it will try to install the driver too. Anyway after a lot of struggles I now have Cuda 12.8+pytorch 2.8 nightly. IT STILL DOESN'T WORK ! It's been 3 days I'm on this, I give up. No texture for me, fine. That's it x)
> 
> Hi, I got exactly the same problem as you and I also update the pytorch 2.8 + cuda 12.8 but still got the error. Same as you.
> 
> Now I fixed the problem , let me explain to you, I think it's related to the wheel we installed (custom_rasterizer)
> 
> First, you can keep pytorch 2.8 and cuda 12.8 (no need to reverse)
> 
> after, you'll need to reinstall the wheel but not the one given , this [ONE ](https://drive.google.com/file/d/1twmIqzqjspovGfFUYzVoz9kPIT62GJRo/view?usp=drive_link)(from this [dude original fix](https://github.com/kijai/ComfyUI-Hunyuan3DWrapper/issues/47#issuecomment-2636352445) )
> 
> So DL the new wheel, replace the old one in the **_ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Hunyuan3DWrapper\wheels_**
> 
> Then reinstall it (guess you're using portable version) so : python_embeded\python.exe -m pip install ComfyUI\custom_nodes\ComfyUI-Hunyuan3DWrapper\wheels\custom_rasterizer-0.1-cp312-cp312-win_amd64.whl
> 
> Hope it helps, GL


I couldn't solve the problem apparently I don't understand how to work with it, I used what was on the git hub, ComfyUI and Hunyuan3DWrapper, then replaced the file custom_rasterizer-0. 1-cp312-cp312-win_amd64.whl and used the command “python_embeded\python.exe -m pip install ComfyUI\custom_nodes\ComfyUI-Hunyuan3DWrapper\wheels\custom_rasterizer-0.1-cp312-cp312-win_amd64.whl”.
but the error didn't disappear I must be doing something wrong, I don't know how to reinstall versions of cuda and pytorch if it is done somewhere in the neural network folders.
can I ask for detailed instructions on how you were able to fix this problem
