### ISSUE TITLE
Windows 11 RTX 2070 SUPER - no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by RoyRoden** [kijai/ComfyUI-Hunyuan3DWrapper#120]
I'm using an NVIDIA GeForce RTX 2070 SUPER, Windows 11, Torch 2.6.0+cu126 - so my setup should be ok.
Most of the nodes work but the node Hy3DRenderMultiView CUDA throws an error: no kernel image is available for execution on the device.
Could it be that the Turing architecture of the 2070 is just too old?

**Comment by joey64x** [comment]
I'm having the same issue on my RTX 3090. Windows 11, Torch 2.6.0+cu126 here as well.

```
Hy3DRenderMultiView
CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Exception raised from c10_cuda_check_implementation at C:\actions-runner\_work\pytorch\pytorch\pytorch\c10\cuda\CUDAException.cpp:43 (most recent call first):
00007FFDDE2991D900007FFDDE299130 c10.dll!c10::Error::Error [<unknown file> @ <unknown line number>]
00007FFDDE297A6A00007FFDDE297A10 c10.dll!c10::detail::torchCheckFail [<unknown file> @ <unknown line number>]
00007FFDF92B4E3F00007FFDF92B4B40 c10_cuda.dll!c10::cuda::c10_cuda_check_implementation [<unknown file> @ <unknown line number>]
00007FFDF92BB10300007FFDF92B61F0 c10_cuda.dll!c10::cuda::warn_or_error_on_sync [<unknown file> @ <unknown line number>]
00007FFDF92B638D00007FFDF92B61F0 c10_cuda.dll!c10::cuda::warn_or_error_on_sync [<unknown file> @ <unknown line number>]
00007FFDDE25AAA300007FFDDE25AA40 c10.dll!c10::StorageImpl::StorageImpl [<unknown file> @ <unknown line number>]
00007FFCC7995A7F00007FFCC7995340 torch_cpu.dll!at::DynamicLibrary::sym [<unknown file> @ <unknown line number>]
00007FFCC7997DEE00007FFCC7997DC0 torch_cpu.dll!at::detail::empty_generic [<unknown file> @ <unknown line number>]
00007FFC8A34657500007FFC8A346490 torch_cuda.dll!at::detail::empty_cuda [<unknown file> @ <unknown line number>]
00007FFC8A34646E00007FFC8A3463B0 torch_cuda.dll!at::detail::empty_cuda [<unknown file> @ <unknown line number>]
00007FFC8A455C7800007FFC8A455C10 torch_cuda.dll!at::native::empty_cuda [<unknown file> @ <unknown line number>]
00007FFC8C16803E00007FFC8C10CCF0 torch_cuda.dll!at::cuda::where_outf [<unknown file> @ <unknown line number>]
00007FFC8C05653E00007FFC8BFE74E0 torch_cuda.dll!at::cuda::bucketize_outf [<unknown file> @ <unknown line number>]
00007FFCC855362C00007FFCC853C070 torch_cpu.dll!at::_ops::xlogy__Tensor::redispatch [<unknown file> @ <unknown line number>]
00007FFCC85C3C9100007FFCC853C070 torch_cpu.dll!at::_ops::xlogy__Tensor::redispatch [<unknown file> @ <unknown line number>]
00007FFCC869E1AE00007FFCC869E0D0 torch_cpu.dll!at::_ops::empty_memory_format::redispatch [<unknown file> @ <unknown line number>]
00007FFCC891C64900007FFCC88F92D0 torch_cpu.dll!at::_ops::view_as_real::redispatch [<unknown file> @ <unknown line number>]
00007FFCC891A56E00007FFCC88F92D0 torch_cpu.dll!at::_ops::view_as_real::redispatch [<unknown file> @ <unknown line number>]
00007FFCC855362C00007FFCC853C070 torch_cpu.dll!at::_ops::xlogy__Tensor::redispatch [<unknown file> @ <unknown line number>]
00007FFCC860B6B800007FFCC860B470 torch_cpu.dll!at::_ops::empty_memory_format::call [<unknown file> @ <unknown line number>]
00007FFCC7ACDD7900007FFCC7AAEF10 torch_cpu.dll!at::functorch::reshape_dim_outof_symint [<unknown file> @ <unknown line number>]
00007FFCC7EFB3B600007FFCC7EFB2B0 torch_cpu.dll!at::native::zeros_symint [<unknown file> @ <unknown line number>]
00007FFCC8B9297A00007FFCC8B8B5F0 torch_cpu.dll!at::compositeexplicitautograd::view_copy_symint_outf [<unknown file> @ <unknown line number>]
00007FFCC8B604FB00007FFCC8B163B0 torch_cpu.dll!at::compositeexplicitautograd::bucketize_outf [<unknown file> @ <unknown line number>]
00007FFCC83CE2E500007FFCC83CE210 torch_cpu.dll!at::_ops::zeros::redispatch [<unknown file> @ <unknown line number>]
00007FFCC8920B0C00007FFCC88F92D0 torch_cpu.dll!at::_ops::view_as_real::redispatch [<unknown file> @ <unknown line number>]
00007FFCC891A44B00007FFCC88F92D0 torch_cpu.dll!at::_ops::view_as_real::redispatch [<unknown file> @ <unknown line number>]
00007FFCC8363A1000007FFCC8363810 torch_cpu.dll!at::_ops::zeros::call [<unknown file> @ <unknown line number>]
00007FFE092D5B8D00007FFE092D56B0 custom_rasterizer_kernel.cp312-win_amd64.pyd!c10::ivalue::Object::operator= [<unknown file> @ <unknown line number>]
00007FFE092F675E00007FFE092F3340 custom_rasterizer_kernel.cp312-win_amd64.pyd!PyInit_custom_rasterizer_kernel [<unknown file> @ <unknown line number>]
00007FFE092F32FD00007FFE092D56B0 custom_rasterizer_kernel.cp312-win_amd64.pyd!c10::ivalue::Object::operator= [<unknown file> @ <unknown line number>]
00007FFE092F4F7400007FFE092F3340 custom_rasterizer_kernel.cp312-win_amd64.pyd!PyInit_custom_rasterizer_kernel [<unknown file> @ <unknown line number>]
00007FFE092F3E9400007FFE092F3340 custom_rasterizer_kernel.cp312-win_amd64.pyd!PyInit_custom_rasterizer_kernel [<unknown file> @ <unknown line number>]
00007FFE092F3F7400007FFE092F3340 custom_rasterizer_kernel.cp312-win_amd64.pyd!PyInit_custom_rasterizer_kernel [<unknown file> @ <unknown line number>]
00007FFE092DEB8D00007FFE092D56B0 custom_rasterizer_kernel.cp312-win_amd64.pyd!c10::ivalue::Object::operator= [<unknown file> @ <unknown line number>]
00007FFDDD86D8A000007FFDDD86D720 python312.dll!PyObject_VectorcallMethod [<unknown file> @ <unknown line number>]
00007FFDDD81069100007FFDDD80FAE0 python312.dll!PyObject_Vectorcall [<unknown file> @ <unknown line number>]
00007FFDDD80FB1500007FFDDD80FAE0 python312.dll!PyObject_Vectorcall [<unknown file> @ <unknown line number>]
00007FFDDD811BA700007FFDDD811440 python312.dll!PyEval_EvalFrameDefault [<unknown file> @ <unknown line number>]
00007FFDDD82F6BA00007FFDDD82F540 python312.dll!PyFunction_Vectorcall [<unknown file> @ <unknown line number>]
00007FFDDD83137100007FFDDD830180 python312.dll!PyDict_GetItemWithError [<unknown file> @ <unknown line number>]
00007FFDDD86C10F00007FFDDD86BF94 python312.dll!PyObject_Call [<unknown file> @ <unknown line number>]
00007FFDDD86C00300007FFDDD86BF94 python312.dll!PyObject_Call [<unknown file> @ <unknown line number>]
00007FFDDD816B6C00007FFDDD811440 python312.dll!PyEval_EvalFrameDefault [<unknown file> @ <unknown line number>]
00007FFDDD82F6BA00007FFDDD82F540 python312.dll!PyFunction_Vectorcall [<unknown file> @ <unknown line number>]
00007FFDDD8313CA00007FFDDD830180 python312.dll!PyDict_GetItemWithError [<unknown file> @ <unknown line number>]
00007FFDDD86C0B900007FFDDD86BF94 python312.dll!PyObject_Call [<unknown file> @ <unknown line number>]
00007FFDDD86C00300007FFDDD86BF94 python312.dll!PyObject_Call [<unknown file> @ <unknown line number>]
00007FFDDD8D53FC00007FFDDD8D5150 python312.dll!PyThread_start_new_thread [<unknown file> @ <unknown line number>]
00007FFDDD8D53A200007FFDDD8D5150 python312.dll!PyThread_start_new_thread [<unknown file> @ <unknown line number>]
00007FFE401337B000007FFE40133660 ucrtbase.dll!wcsrchr [<unknown file> @ <unknown line number>]
00007FFE41B1E8D700007FFE41B1E8C0 KERNEL32.DLL!BaseThreadInitThunk [<unknown file> @ <unknown line number>]
00007FFE42DD14FC00007FFE42DD14D0 ntdll.dll!RtlUserThreadStart [<unknown file> @ <unknown line number>]
```

**Comment by joey64x** [comment]
I was able to solve this by compiling my own rasterizer. This is what I did.

From Comfy UI folder:
`cd custom_nodes\ComfyUI-Hunyuan3DWrapper\hy3dgen\texgen\custom_rasterizer`

Compile the rasterizer:
`python setup.py bdist_wheel` - don't use python setup.py install because that will generate things in a deprecated way

Once that's completed, install the wheel and re-install over the old one:
`pip install dist\custom_rasterizer-0.1.0+torch260.cuda126-cp312-cp312-win_amd64.whl --force-reinstall`

Full path of the wheel it builds from the ComfyUI folder would be: 
`custom_nodes\ComfyUI-Hunyuan3DWrapper\hy3dgen\texgen\custom_rasterizer\dist\custom_rasterizer-0.1.0+torch260.cuda126-cp312-cp312-win_amd64.whl `

**Comment by RoyRoden** [comment]
> I was able to solve this by compiling my own rasterizer. This is what I did.
> 
> From Comfy UI folder: `cd custom_nodes\ComfyUI-Hunyuan3DWrapper\hy3dgen\texgen\custom_rasterizer`
> 
> Compile the rasterizer: `python setup.py bdist_wheel` - don't use python setup.py install because that will generate things in a deprecated way
> 
> Once that's completed, install the wheel and re-install over the old one: `pip install dist\custom_rasterizer-0.1.0+torch260.cuda126-cp312-cp312-win_amd64.whl --force-reinstall`
> 
> Full path of the wheel it builds from the ComfyUI folder would be: `custom_nodes\ComfyUI-Hunyuan3DWrapper\hy3dgen\texgen\custom_rasterizer\dist\custom_rasterizer-0.1.0+torch260.cuda126-cp312-cp312-win_amd64.whl `

Thank you! I will try this soon.

**Comment by Pajaso22** [comment]
You are my HERO too. After two week of battle, thanks your advices, everything start works perfectly. Thanks.
