### ISSUE TITLE
Can't build own wheel

### ISSUE THREAD

**Issue by simonEichh** [kijai/ComfyUI-Hunyuan3DWrapper#47]
Hello, I had the same CUDA error as here in issue #17 so I wanted to build my own wheel. However I keep getting a Microsoft Visual Studio error when I build it with my own Python environment (error: `....\custom_rasterizer_kernel\grid_neighbor.cpp : fatal error C1083: Cannot open compiler generated file: '': Invalid argument error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.42.34433\\bin\\HostX86\\x64\\cl.exe' failed with exit code 1`) and if i build it with the embedded python i get the error `C:\Users\simon\OneDrive\Master\Master Thesis\comfyyUI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\include\torch/csrc/python_headers.h(12): fatal error C1083: Cannot open include file: 'Python.h': No such file or directory
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.42.34433\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2.`

What exactly is the requirement? I have the MSVC v140 C++ build tools installed and i'm unsure what to do now. I also tried it with the v142 build tools. I'd be glad if someone could give me some help! I'm quite new so i apologize in advance if the issue is obvious :D

torch version: 2.6.0+cu124
python version: 3.12.8

**Comment by jugadorgl1** [comment]
There was the same error with the portable version. Nothing helped.
I installed Python 3.12 and the regular version of ComfyUI. In this combination, the Wheel was built without any problems.

**Comment by simonEichh** [comment]
I figured out that the problem was actually that my filepath was longer than 256 which is allowed in windows filesystems. I moved my folder and now it built the wheel but it still doesn't work. It seems like it built the wheel in my own windows python environment. I don't have a venv folder in my portable comfyui installation. Do i just move the built wheel into the lib/site-packages folder? Do I need to build it with the embeded python? I'm a bit confused haha

**Comment by Krishna6346** [comment]
> There was the same error with the portable version. Nothing helped. I installed Python 3.12 and the regular version of ComfyUI. In this combination, the Wheel was built without any problems.
> 
> Maybe it will help someone, my **custom_rasterizer** and **mesh_processor** Whl files. Python 3.12.8 +Cuda 12.6 https://drive.google.com/drive/folders/1YJx-YQ658p3-uFBB3MTcbtrwRHD8n9xZ?usp=drive_link

thanks a lot buddy, it works for me after so much try in portable latest comfyui

**Comment by simonEichh** [comment]
how do i update the cuda drivers that my comfyui portable uses? im still using 12.4

**Comment by simonEichh** [comment]
idk what i did but it works now, the delighting does really weird stuff though. Like it paints random red spots in the face of the character. any tipps on better delighting?

**Comment by kijai** [comment]
> idk what i did but it works now, the delighting does really weird stuff though. Like it paints random red spots in the face of the character. any tipps on better delighting?

Adjust the background level of the image, if you get too much red it often helps to have fully white background, it's set to 0.8 by default in the example workflow. Other than  that, just try different seeds, its a diffusion process so it has randomness. And it also just doesn't work well for all images, you can also fully skip it in those cases.

**Comment by simonEichh** [comment]
> > idk what i did but it works now, the delighting does really weird stuff though. Like it paints random red spots in the face of the character. any tipps on better delighting?
> 
> Adjust the background level of the image, if you get too much red it often helps to have fully white background, it's set to 0.8 by default in the example workflow. Other than that, just try different seeds, its a diffusion process so it has randomness. And it also just doesn't work well for all images, you can also fully skip it in those cases.

Thank u! I noticed that higher mask value returns better results. It's actually set to 0.5 in the example workflow though

**Comment by qintongtongAq** [comment]
> [您好，我遇到了与问题#17](https://github.com/kijai/ComfyUI-Hunyuan3DWrapper/issues/17)中相同的 CUDA 错误，所以我想自己构建一个 wheel。但是，当我使用自己的 Python 环境构建它时，我总是收到 Microsoft Visual Studio 错误 (错误：) `....\custom_rasterizer_kernel\grid_neighbor.cpp : fatal error C1083: Cannot open compiler generated file: '': Invalid argument error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.42.34433\\bin\\HostX86\\x64\\cl.exe' failed with exit code 1`，如果我使用嵌入式 Python 构建它，我会收到错误`C:\Users\simon\OneDrive\Master\Master Thesis\comfyyUI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\include\torch/csrc/python_headers.h(12): fatal error C1083: Cannot open include file: 'Python.h': No such file or directory error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.42.34433\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2.`
> 
> 具体要求是什么？我安装了 MSVC v140 C++ 构建工具，但我不知道现在该怎么做。我也尝试使用 v142 构建工具。如果有人能给我一些帮助，我会很高兴！我是新手，所以如果问题很明显，我提前道歉 :D
> 
> torch版本：2.6.0+cu124 python版本：3.12.8




use vs2019, not vs2022

**Comment by krissh18** [comment]
> There was the same error with the portable version. Nothing helped. I installed Python 3.12 and the regular version of ComfyUI. In this combination, the Wheel was built without any problems.
> 
> Maybe it will help someone, my **custom_rasterizer** and **mesh_processor** Whl files. Python 3.12.8 +Cuda 12.6 https://drive.google.com/drive/folders/1YJx-YQ658p3-uFBB3MTcbtrwRHD8n9xZ?usp=drive_link

Thank you so much buddy. It works great for the latest portable version of comfy. Have been struggling for last 2 days for this, And this works great. Thanks!

**Comment by dsammy436** [comment]
> There was the same error with the portable version. Nothing helped. I installed Python 3.12 and the regular version of ComfyUI. In this combination, the Wheel was built without any problems.
> 
> Maybe it will help someone, my **custom_rasterizer** and **mesh_processor** Whl files. Python 3.12.8 +Cuda 12.6 https://drive.google.com/drive/folders/1YJx-YQ658p3-uFBB3MTcbtrwRHD8n9xZ?usp=drive_link

You came in as a CLUTCH!!! Thanksss!

**Comment by edasque** [comment]
Where do you place those WHL files?

**Comment by darkssektor** [comment]
> There was the same error with the portable version. Nothing helped. I installed Python 3.12 and the regular version of ComfyUI. In this combination, the Wheel was built without any problems.
> 
> Maybe it will help someone, my **custom_rasterizer** and **mesh_processor** Whl files. Python 3.12.8 +Cuda 12.6 https://drive.google.com/drive/folders/1YJx-YQ658p3-uFBB3MTcbtrwRHD8n9xZ?usp=drive_link

Help me, I haven't been able to solve this problem for a long time, your file also didn't help, my RTX2060 video card, can I ask you to make a similar file for my system, and if your file should work, then can you tell me what might be wrong?

**Comment by grovergol** [comment]
In case anyone needs a wheel for Windows 10, Python 3.12.10, torch 2.7.1 + cuda 12.8
https://www.dropbox.com/scl/fi/cxtytq9n49nujv1hilxw0/custom_rasterizer_0_1_0-torch271_cuda128_cp312_cp312_win_amd64.whl?rlkey=8qnwmu6u8rmcjmdhb1k092g77&st=v8gmtb5e&dl=0
