### ISSUE TITLE
CUDA Error in Hy3DRenderMultiView node: no kernel image is available

### ISSUE THREAD

**Issue by kvick-games** [kijai/ComfyUI-Hunyuan3DWrapper#7]
![Image](https://github.com/user-attachments/assets/2eb68bbb-b730-4855-ae8b-07fdf1cb473d)

Error in text:
**Hy3DRenderMultiView**
CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

I tried running this on a regular comfy install and a portable install and am getting this error.
Tried running through all of the additional setup commands listed in the readme.

Running on 3080ti
Windows 11
CUDA version:
Cuda compilation tools, release 12.6, V12.6.85
Build cuda_12.6.r12.6/compiler.35059454_0

Torch:
2.6.0.dev20241223+cu124 
Torch CUDA 12.4

Python 3.12.8

not sure what other info I'd need to provide.

also got this callstack but I'm not sure if this is the exact source of the error:

![Image](https://github.com/user-attachments/assets/f955d45b-d982-48b9-8aca-dd17b467abb4)

**Comment by Siempreflaco** [comment]
I had this issue in the portable version of comfy. I removed custom_rasterize because I had installed the wheel that he provided.

`python.exe -m pip uninstall custom_rasterize`

Then I built my own wheel with

`python setup.py bdist_wheel`

That creates a wheel in **hy3dgen\texgen\custom_rasterizer\dist\custom_rasterizer-0.1-cp312-cp312-win_amd64.whl**

Then I pip installed that wheel (_if you move or copy the file to ComfyUI_windows_portable it makes it easier to install_)

`python_embeded\python.exe -m pip install custom_rasterizer-0.1-cp312-cp312-win_amd64.whl`

**Comment by xinfangyuzhou** [comment]
我也遇到同样的问题如何解决

**Comment by kvick-games** [comment]
@Siempreflaco dude thank you so much, I was banging my head against this all day.

**Comment by danganbenpa** [comment]
> I had this issue in the portable version of comfy. I removed custom_rasterize because I had installed the wheel that he provided.
> 
> `python.exe -m pip uninstall custom_rasterize`
> 
> Then I built my own wheel with
> 
> `python setup.py bdist_wheel`
> 
> That creates a wheel in **hy3dgen\texgen\custom_rasterizer\dist\custom_rasterizer-0.1-cp312-cp312-win_amd64.whl**
> 
> Then I pip installed that wheel (_if you move or copy the file to ComfyUI_windows_portable it makes it easier to install_)
> 
> `python_embeded\python.exe -m pip install custom_rasterizer-0.1-cp312-cp312-win_amd64.whl`

That first part I just get 'WARNING: Skipping custom_rasterize as it is not installed.' Second part I get is a messages saying it can't find the file/path. 

Doing this from main comfyui folder doesn't help. Neither does doing it from inside the ComfyUI-Hunyuan3DWrapper module folder. I'm very bad at this. Could you explain where I need to navigate to to run each of these commands?

**Comment by Siempreflaco** [comment]
> > I had this issue in the portable version of comfy. I removed custom_rasterize because I had installed the wheel that he provided.
> > `python.exe -m pip uninstall custom_rasterize`
> > Then I built my own wheel with
> > `python setup.py bdist_wheel`
> > That creates a wheel in **hy3dgen\texgen\custom_rasterizer\dist\custom_rasterizer-0.1-cp312-cp312-win_amd64.whl**
> > Then I pip installed that wheel (_if you move or copy the file to ComfyUI_windows_portable it makes it easier to install_)
> > `python_embeded\python.exe -m pip install custom_rasterizer-0.1-cp312-cp312-win_amd64.whl`
> 
> That first part I just get 'WARNING: Skipping custom_rasterize as it is not installed.' Second part I get is a messages saying it can't find the file/path.
> 
> Doing this from main comfyui folder doesn't help. Neither does doing it from inside the ComfyUI-Hunyuan3DWrapper module folder. I'm very bad at this. Could you explain where I need to navigate to to run each of these commands?

the first command you want to run from the **python_embeded** folder to remove the custom_rasterize if you have it installed.

The second command needs to be ran from the custom node provided (_ComfyUI-Hunyuan3DWrapper_) it should be in **ComfyUI\custom_nodes\ComfyUI-Hunyuan3DWrapper**

within the custom node there is a folder named **hy3dgen** go into that folder and there should be another named **texgen** and finally go into the folder named **custom_rasterizer** that's where the **setup.py** lives.

once you are there you can click on your search bar and **type cmd and hit enter** this will open the command prompt to that location and that's where you run 

`python setup.py bdist_wheel`

![Image](https://github.com/user-attachments/assets/270f32a4-a5e2-4c86-a13a-61439aaef49c)

**Comment by danganbenpa** [comment]
Okay. Running from thcustom_rasterizer folder I get this:

E:\AI\ComfyUI_windows_portable_NEW\ComfyUI\custom_nodes\ComfyUI-Hunyuan3DWrapper\hy3dgen\texgen\custom_rasterizer>python setup.py bdist_wheel
Traceback (most recent call last):
  File "E:\AI\ComfyUI_windows_portable_NEW\ComfyUI\custom_nodes\ComfyUI-Hunyuan3DWrapper\hy3dgen\texgen\custom_rasterizer\setup.py", line 8, in <module>
    custom_rasterizer_module = CUDAExtension('custom_rasterizer_kernel', [
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\noodl\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\utils\cpp_extension.py", line 1078, in CUDAExtension
    library_dirs += library_paths(cuda=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\noodl\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\utils\cpp_extension.py", line 1216, in library_paths
    paths.append(_join_cuda_home(lib_dir))
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\noodl\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\utils\cpp_extension.py", line 2416, in _join_cuda_home
    raise OSError('CUDA_HOME environment variable is not set. '
OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.

**Comment by danganbenpa** [comment]
Okay I think I solved that but now I'm getting

E:\AI\ComfyUI_windows_portable_NEW\ComfyUI\custom_nodes\ComfyUI-Hunyuan3DWrapper\hy3dgen\texgen\custom_rasterizer>python setup.py bdist_wheel
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'bdist_wheel'

**Comment by danganbenpa** [comment]
Okay! I installed wheel and then that command did run but with some errors. After that the only wheel file I could find was "custom_rasterizer-0.1-cp311-cp311-win_amd64.whl", and I put that in my comfyui portable folder and altered the command to refer to that file nevaise I don't have a cp312 one and it gave me 

"custom_rasterizer-0.1-cp311-cp311-win_amd64.whl is not a supported wheel on this platform."

**Comment by danganbenpa** [comment]
I found an instance of the cp312 one/ This is what I get when I try install it:

Microsoft Windows [Version 10.0.22631.4751]
(c) Microsoft Corporation. All rights reserved.

E:\AI\ComfyUI_windows_portable_NEW>python_embeded\python.exe -m pip install ComfyUI\custom_nodes\ComfyUI-Hunyuan3DWrapper\wheels\custom_rasterizer-0.1-cp312-cp312-win_amd64.whl
Processing e:\ai\comfyui_windows_portable_new\comfyui\custom_nodes\comfyui-hunyuan3dwrapper\wheels\custom_rasterizer-0.1-cp312-cp312-win_amd64.whl
custom-rasterizer is already installed with the same version as the provided wheel. Use --force-reinstall to force an installation of the wheel.

E:\AI\ComfyUI_windows_portable_NEW>python_embeded\python.exe -m pip install ComfyUI\custom_nodes\ComfyUI-Hunyuan3DWrapper\wheels\custom_rasterizer-0.1-cp312-cp312-win_amd64.whl --force reinstall
Processing e:\ai\comfyui_windows_portable_new\comfyui\custom_nodes\comfyui-hunyuan3dwrapper\wheels\custom_rasterizer-0.1-cp312-cp312-win_amd64.whl
ERROR: Could not find a version that satisfies the requirement reinstall (from versions: none)
ERROR: No matching distribution found for reinstall

E:\AI\ComfyUI_windows_portable_NEW>python_embeded\python.exe -m pip uninstall custom_rasterize
WARNING: Skipping custom_rasterize as it is not installed.

E:\AI\ComfyUI_windows_portable_NEW>


It appears that for the sake of uninstallation it doesn't exist, but for the sake of installation it's already installed so I can't install it. So confused right now.

**Comment by danganbenpa** [comment]
This is what I get when I run 'python setup.py bdist_wheel'

E:\AI\ComfyUI_windows_portable_NEW\ComfyUI\custom_nodes\ComfyUI-Hunyuan3DWrapper\hy3dgen\texgen\custom_rasterizer>python setup.py bdist_wheel
running bdist_wheel
running build
running build_py
running egg_info
writing custom_rasterizer.egg-info\PKG-INFO
writing dependency_links to custom_rasterizer.egg-info\dependency_links.txt
writing top-level names to custom_rasterizer.egg-info\top_level.txt
reading manifest file 'custom_rasterizer.egg-info\SOURCES.txt'
writing manifest file 'custom_rasterizer.egg-info\SOURCES.txt'
running build_ext
C:\Users\noodl\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\utils\cpp_extension.py:382: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified
  warnings.warn(f'Error checking compiler version for {compiler}: {error}')
building 'custom_rasterizer_kernel' extension
C:\Users\noodl\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\utils\cpp_extension.py:1964: UserWarning: TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation.
If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'].
  warnings.warn(
Emitting ninja build file E:\AI\ComfyUI_windows_portable_NEW\ComfyUI\custom_nodes\ComfyUI-Hunyuan3DWrapper\hy3dgen\texgen\custom_rasterizer\build\temp.win-amd64-cpython-311\Release\build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.42.34433\bin\HostX86\x64\link.exe" /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\Users\noodl\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\lib "/LIBPATH:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4\lib\x64" /LIBPATH:C:\Users\noodl\AppData\Local\Programs\Python\Python311\libs /LIBPATH:C:\Users\noodl\AppData\Local\Programs\Python\Python311 /LIBPATH:C:\Users\noodl\AppData\Local\Programs\Python\Python311\PCbuild\amd64 "/LIBPATH:C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.42.34433\ATLMFC\lib\x64" "/LIBPATH:C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.42.34433\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.22621.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\\lib\10.0.22621.0\\um\x64" c10.lib torch.lib torch_cpu.lib torch_python.lib cudart.lib c10_cuda.lib torch_cuda.lib /EXPORT:PyInit_custom_rasterizer_kernel E:\AI\ComfyUI_windows_portable_NEW\ComfyUI\custom_nodes\ComfyUI-Hunyuan3DWrapper\hy3dgen\texgen\custom_rasterizer\build\temp.win-amd64-cpython-311\Release\lib/custom_rasterizer_kernel/grid_neighbor.obj E:\AI\ComfyUI_windows_portable_NEW\ComfyUI\custom_nodes\ComfyUI-Hunyuan3DWrapper\hy3dgen\texgen\custom_rasterizer\build\temp.win-amd64-cpython-311\Release\lib/custom_rasterizer_kernel/rasterizer.obj E:\AI\ComfyUI_windows_portable_NEW\ComfyUI\custom_nodes\ComfyUI-Hunyuan3DWrapper\hy3dgen\texgen\custom_rasterizer\build\temp.win-amd64-cpython-311\Release\lib/custom_rasterizer_kernel/rasterizer_gpu.obj /OUT:build\lib.win-amd64-cpython-311\custom_rasterizer_kernel.cp311-win_amd64.pyd /IMPLIB:E:\AI\ComfyUI_windows_portable_NEW\ComfyUI\custom_nodes\ComfyUI-Hunyuan3DWrapper\hy3dgen\texgen\custom_rasterizer\build\temp.win-amd64-cpython-311\Release\lib/custom_rasterizer_kernel\custom_rasterizer_kernel.cp311-win_amd64.lib
   Creating library E:\AI\ComfyUI_windows_portable_NEW\ComfyUI\custom_nodes\ComfyUI-Hunyuan3DWrapper\hy3dgen\texgen\custom_rasterizer\build\temp.win-amd64-cpython-311\Release\lib/custom_rasterizer_kernel\custom_rasterizer_kernel.cp311-win_amd64.lib and object E:\AI\ComfyUI_windows_portable_NEW\ComfyUI\custom_nodes\ComfyUI-Hunyuan3DWrapper\hy3dgen\texgen\custom_rasterizer\build\temp.win-amd64-cpython-311\Release\lib/custom_rasterizer_kernel\custom_rasterizer_kernel.cp311-win_amd64.exp
Generating code
Finished generating code
C:\Users\noodl\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
installing to build\bdist.win-amd64\wheel
running install
running install_lib
creating build\bdist.win-amd64\wheel
creating build\bdist.win-amd64\wheel\custom_rasterizer
copying build\lib.win-amd64-cpython-311\custom_rasterizer\io_glb.py -> build\bdist.win-amd64\wheel\.\custom_rasterizer
copying build\lib.win-amd64-cpython-311\custom_rasterizer\io_obj.py -> build\bdist.win-amd64\wheel\.\custom_rasterizer
copying build\lib.win-amd64-cpython-311\custom_rasterizer\render.py -> build\bdist.win-amd64\wheel\.\custom_rasterizer
copying build\lib.win-amd64-cpython-311\custom_rasterizer\__init__.py -> build\bdist.win-amd64\wheel\.\custom_rasterizer
copying build\lib.win-amd64-cpython-311\custom_rasterizer_kernel.cp311-win_amd64.pyd -> build\bdist.win-amd64\wheel\.
running install_egg_info
Copying custom_rasterizer.egg-info to build\bdist.win-amd64\wheel\.\custom_rasterizer-0.1-py3.11.egg-info
running install_scripts
C:\Users\noodl\AppData\Local\Programs\Python\Python311\Lib\site-packages\wheel\_bdist_wheel.py:124: RuntimeWarning: Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
  if get_flag("Py_DEBUG", hasattr(sys, "gettotalrefcount"), warn=(impl == "cp")):
creating build\bdist.win-amd64\wheel\custom_rasterizer-0.1.dist-info\WHEEL
creating 'dist\custom_rasterizer-0.1-cp311-cp311-win_amd64.whl' and adding 'build\bdist.win-amd64\wheel' to it
adding 'custom_rasterizer_kernel.cp311-win_amd64.pyd'
adding 'custom_rasterizer/__init__.py'
adding 'custom_rasterizer/io_glb.py'
adding 'custom_rasterizer/io_obj.py'
adding 'custom_rasterizer/render.py'
adding 'custom_rasterizer-0.1.dist-info/METADATA'
adding 'custom_rasterizer-0.1.dist-info/WHEEL'
adding 'custom_rasterizer-0.1.dist-info/top_level.txt'
adding 'custom_rasterizer-0.1.dist-info/RECORD'
removing build\bdist.win-amd64\wheel

There are errors in here. I don't know if any of them are the cause of this not working.

**Comment by dvdrbls** [comment]
Thank you, it worked

**Comment by justinwking** [comment]
I had trouble with this step because even though cuda was installed on my system, and worked with anaconda the python version I was using did not recognize cuda. So before doing install, I did the following command

`python setup.py check`

If this does not yield error messages you might be able to install. If it says that cuda is missing. You might need to updated the drivers, reinstall pytorch for the python version you are using... You might even have to install libtorch( I installed it, but don't know if it was needed. I also installed ninja. once I go those things done, I tried to install it, and it installed without problems... But I had to make sure it install it in my conda environment and that's when it worked.

**Comment by MicahJank** [comment]
> > > I had this issue in the portable version of comfy. I removed custom_rasterize because I had installed the wheel that he provided.    Then I built my own wheel with   That creates a wheel in **hy3dgen\texgen\custom_rasterizer\dist\custom_rasterizer-0.1-cp312-cp312-win_amd64.whl** Then I pip installed that wheel (_if you move or copy the file to ComfyUI_windows_portable it makes it easier to install_`python.exe -m pip uninstall custom_rasterize``python setup.py bdist_wheel`)
> > > `python_embeded\python.exe -m pip install custom_rasterizer-0.1-cp312-cp312-win_amd64.whl`
> > 
> > 
> > That first part I just get 'WARNING: Skipping custom_rasterize as it is not installed.' Second part I get is a messages saying it can't find the file/path.
> > Doing this from main comfyui folder doesn't help. Neither does doing it from inside the ComfyUI-Hunyuan3DWrapper module folder. I'm very bad at this. Could you explain where I need to navigate to to run each of these commands?
> 
> the first command you want to run from the **python_embeded** folder to remove the custom_rasterize if you have it installed.
> 
> The second command needs to be ran from the custom node provided (_ComfyUI-Hunyuan3DWrapper_) it should be in **ComfyUI\custom_nodes\ComfyUI-Hunyuan3DWrapper**
> 
> within the custom node there is a folder named **hy3dgen** go into that folder and there should be another named **texgen** and finally go into the folder named **custom_rasterizer** that's where the **setup.py** lives.
> 
> once you are there you can click on your search bar and **type cmd and hit enter** this will open the command prompt to that location and that's where you run
> 
> `python setup.py bdist_wheel`
> 
> ![Image](https://github.com/user-attachments/assets/270f32a4-a5e2-4c86-a13a-61439aaef49c)

Just so people are aware...i also go the 'custom_rasterize' is not installed warning...in my case the module is was actually 'custom_rasterizer' with an 'r' at the end. Not sure if just a typo or it can be different but once i used to command `python.exe -m pip uninstall custom_rasterizer` it successfully uninstalled

**Comment by Siempreflaco** [comment]
> Just so people are aware...i also got the 'custom_rasterize' is not installed warning...in my case the module was actually 'custom_rasterizer' with an 'r' at the end. Not sure if just a typo or it can be different but once i used to command `python.exe -m pip uninstall custom_rasterizer` it successfully uninstalled

that was a typo on my end...updated comment to prevent any confusion.
